# Generated by Django 4.2.5 on 2023-10-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rut',
        ),
    ]
