# Generated by Django 4.1.6 on 2023-10-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_userprofile_comuna_remove_userprofile_rut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provincia",
            name="id_region",
        ),
        migrations.DeleteModel(
            name="comuna",
        ),
        migrations.DeleteModel(
            name="provincia",
        ),
        migrations.DeleteModel(
            name="region",
        ),
    ]
