# Generated by Django 4.2.5 on 2023-11-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_orderitem_order_productos_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total',
        ),
    ]
