# Generated by Django 4.1.6 on 2023-11-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_rename_address_order_direccion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparacion", "Preparación"),
                    ("horno", "Horno"),
                    ("despacho", "Despacho"),
                    ("entregado", "Entregado"),
                    ("finalizado", "Finalizado"),
                ],
                default="preparacion",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tiempo_estimado",
            field=models.IntegerField(default=0),
        ),
    ]
