# Generated by Django 4.1.6 on 2023-11-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_order_status_order_tiempo_estimado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Preparación", "Preparación"),
                    ("Horno", "Horno"),
                    ("Despacho", "Despacho"),
                    ("Entregado", "Entregado"),
                    ("Finalizado", "Finalizado"),
                ],
                default="preparacion",
                max_length=20,
            ),
        ),
    ]
