# Generated by Django 4.1.6 on 2023-11-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparacion", "Preparación"),
                    ("horno", "Horno"),
                    ("despacho", "Despacho"),
                    ("entregado", "Entregado"),
                    ("finalizado", "Finalizado"),
                ],
                default="preparacion",
                max_length=20,
            ),
        ),
    ]
