# Generated by Django 4.1.6 on 2023-11-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="tiempo_estimado",
            field=models.IntegerField(default=80),
        ),
    ]
