# Generated by Django 4.2.5 on 2023-11-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_contacto_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='valoracion',
            field=models.PositiveIntegerField(),
        ),
    ]
