# Generated by Django 4.2.5 on 2023-11-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_contacto_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='mostrar_comentarios',
            field=models.BooleanField(default=False),
        ),
    ]
